version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7.36
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            #- ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            tcp_network:
                aliases:
                - dev
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.1
        links: 
            - db:db
        ports:
            - 8001:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test 
            MYSQL_ROOT_PASSWORD: test
            PMA_ARBITRARY: 1
            PMA_HOST: db
        networks:
            tcp_network:
                aliases:
                - dev    
        
volumes:
    persistent:
networks:
  tcp_network:
      driver: bridge
